#!/usr/bin/env zsh

# Location sources oh-my-zsh
export ZSH=/Users/redknife/.oh-my-zsh

# Oh-my-zsh configuration
ZSH_THEME="robbyrussell"
ENABLE_CORRECTION="false"

source $HOME/Developer/rs/dotfiles/zsh/envs.zsh
source $HOME/Developer/rs/dotfiles/zsh/aliases.zsh
source $HOME/Developer/rs/dotfiles/zsh/functions.zsh

plugins=(
  compleat
  ssh-agent
  git osx brew
  vagrant
  extract last-working-dir
  npm nvm
  z
  # zsh-nvm
  # pyenv pip
)

# Load oh-my-zsh
source $ZSH/oh-my-zsh.sh
